{% set python_min = "3.10" %}

{% set name = "pangaeapy" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pangaeapy-{{ version }}.tar.gz
  sha256: 3c4b8014869e5060d576e9c8076b85a34d787a67c06afdd6cc06fbfe8365f6b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - aiohttp >=3.11.0
    - python >={{ python_min }}
    - cftime >=1.6.3
    - lxml >=4.9.3
    - requests >=2.26.0
    - pandas >=2.2.2
    - numpy >=1.24.4
    - netcdf4 >1.6.5

test:
  imports:
    - pangaeapy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pangaea-data-publisher/pangaeapy
  summary: PANGAEA Python Client
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
