{% set name = "pangaeapy" %}
{% set version = "1.0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pangaeapy-{{ version }}.tar.gz
  sha256: a4a2851f9028b3449e2c894ceb560464741b09b2ea729cb770894b809d463691

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - cftime >=1.6.3
    - lxml >=4.9.3
    - requests >=2.26.0
    - pandas >=2.0.3
    - numpy >=2.0.0
    - netcdf4 >=1.7.2

test:
  imports:
    - pangaeapy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pangaea-data-publisher/pangaeapy
  summary: PANGAEA Python Client
  license: GPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
