{% set name = "pangaeapy" %}
{% set version = "1.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pangaeapy-{{ version }}.tar.gz
  sha256: e3fa2211afb4f4b4820684e45ab3f4656bc190ad38c8681af0c6c5422709da36

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - cftime >=1.6.3
    - lxml >=4.9.3
    - requests >=2.26.0
    - pandas >=2.0.3
    - numpy >=1.24.4
    - netcdf4 >=1.6.3,<1.7.dev0

test:
  imports:
    - pangaeapy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pangaea-data-publisher/pangaeapy
  summary: PANGAEA Python Client
  license: GPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
