schema_version: 1

context:
  version: "1.1.3"

package:
  name: pangaeapy
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pangaeapy/pangaeapy-${{ version }}.tar.gz
  sha256: 613c87b5720299a0d94655247b000efa40deaac8451d8c856a84c65c727dd6b5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=80.0
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - aiohttp >=3.11.0
    - jmespath >=1.0.0
    - lxml >=4.9.3
    - netcdf4 >1.6.5
    - numpy >=1.24.4
    - pandas >=2.2.2
    - requests >=2.26.0

tests:
  - python:
      imports:
        - pangaeapy
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Download and analyse (meta-)data of PANGAEA datasets
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://www.pangaea.de
  repository: https://github.com/pangaea-data-publisher/pangaeapy
  documentation: https://pangaea-data-publisher.github.io/pangaeapy/

extra:
  recipe-maintainers:
    - ocefpaf
